"""Process-neutral Magic PEX generation primitives.

The process manifest owns layer semantics, device recognition, source units, and
provenance.  This module only renders those process-specific facts into Magic's
technology-file grammar.  It deliberately keeps a raw-directive escape hatch
for source decks whose geometry semantics cannot be represented by the small
normalized directive vocabulary yet.
"""

from __future__ import annotations

from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import re
from typing import Any


GENERATED_PREFIX = "/* GENERATED by scripts/gen_magic_pex.py; do not edit. */"


class MagicPexError(ValueError):
    """Raised when a PEX manifest cannot be rendered safely."""


def _decimal(value: object) -> Decimal:
    try:
        return Decimal(str(value))
    except Exception as exc:  # pragma: no cover - defensive error context
        raise MagicPexError(f"not a numeric PEX value: {value!r}") from exc


def _integer(value: object) -> int:
    return int(_decimal(value).quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def _unit_name(unit: object) -> str:
    return str(unit).strip().lower().replace("/", "_per_").replace("²", "2")


def convert_to_magic(value: object, unit: object, lambda_um: object) -> int:
    """Convert a source coefficient to Magic's integer extraction units.

    Magic uses milliohms/square, attofarads/lambda^2, and
    attofarads/lambda.  The source unit is mandatory for normalized
    directives; this prevents a new process from silently inheriting the
    LS1u fF-based assumptions.
    """

    number = _decimal(value)
    unit_name = _unit_name(unit)
    lam = _decimal(lambda_um)
    if lam <= 0:
        raise MagicPexError(f"lambda must be positive, got {lambda_um!r}")

    if unit_name in {"ohm_per_square", "ohm_sq", "ohms_per_square"}:
        return _integer(number * Decimal("1000"))
    if unit_name in {"milliohm_per_square", "mohm_per_square", "milliohms_per_square"}:
        return _integer(number)
    if unit_name in {"ohm_per_contact", "ohms_per_contact"}:
        return _integer(number * Decimal("1000"))
    if unit_name in {"milliohm_per_contact", "mohm_per_contact", "milliohms_per_contact"}:
        return _integer(number)
    if unit_name in {"af_per_lambda2", "attofarad_per_lambda2", "attofarads_per_lambda2"}:
        return _integer(number)
    if unit_name in {"af_per_lambda", "attofarad_per_lambda", "attofarads_per_lambda"}:
        return _integer(number)
    if unit_name in {"af_per_um2", "attofarad_per_um2", "attofarads_per_um2"}:
        return _integer(number * lam * lam)
    if unit_name in {"af_per_um", "attofarad_per_um", "attofarads_per_um"}:
        return _integer(number * lam)
    if unit_name in {"ff_per_um2", "femtofarad_per_um2", "femtofarads_per_um2"}:
        return _integer(number * Decimal("1000") * lam * lam)
    if unit_name in {"ff_per_um", "femtofarad_per_um", "femtofarads_per_um"}:
        return _integer(number * Decimal("1000") * lam)
    raise MagicPexError(f"unsupported source unit {unit!r}")


def capacitance_to_magic(value: object, unit: object, lambda_um: object) -> str:
    """Convert a capacitance coefficient without discarding sub-attofarad precision."""

    number = _decimal(value)
    unit_name = _unit_name(unit)
    lam = _decimal(lambda_um)
    if lam <= 0:
        raise MagicPexError(f"lambda must be positive, got {lambda_um!r}")
    if unit_name in {"af_per_lambda2", "attofarad_per_lambda2", "attofarads_per_lambda2"}:
        converted = number
    elif unit_name in {"af_per_lambda", "attofarad_per_lambda", "attofarads_per_lambda"}:
        converted = number
    elif unit_name in {"af_per_um2", "attofarad_per_um2", "attofarads_per_um2"}:
        converted = number * lam * lam
    elif unit_name in {"af_per_um", "attofarad_per_um", "attofarads_per_um"}:
        converted = number * lam
    elif unit_name in {"ff_per_um2", "femtofarad_per_um2", "femtofarads_per_um2"}:
        converted = number * Decimal("1000") * lam * lam
    elif unit_name in {"ff_per_um", "femtofarad_per_um", "femtofarads_per_um"}:
        converted = number * Decimal("1000") * lam
    else:
        raise MagicPexError(f"unsupported capacitance unit {unit!r}")
    return format(converted.normalize(), "f")



def sheet_to_magic_mohm(value_ohm_sq: object) -> int:
    """Compatibility conversion used by the original LS1u manifest."""

    return convert_to_magic(value_ohm_sq, "ohm_per_square", 1)


def area_cap_to_magic_af_per_lambda2(value_ff_um2: object, lambda_um: object) -> int:
    """Compatibility conversion for the LS1u fF/um^2 manifest field."""

    return convert_to_magic(value_ff_um2, "ff_per_um2", lambda_um)


def edge_cap_to_magic_af_per_lambda(value_ff_um: object, lambda_um: object) -> int:
    """Compatibility conversion for the LS1u fF/um manifest field."""

    return convert_to_magic(value_ff_um, "ff_per_um", lambda_um)


def _replace_section(text: str, name: str, replacement: str) -> str:
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == name)
    except StopIteration as exc:
        raise MagicPexError(f"technology base has no {name} section") from exc
    try:
        end = next(
            i for i in range(start + 1, len(lines)) if lines[i].strip() == "end"
        )
    except StopIteration as exc:
        raise MagicPexError(f"technology {name} section has no end") from exc
    replacement_lines = replacement.rstrip("\n").splitlines()
    return "\n".join(lines[:start] + replacement_lines + lines[end + 1 :]) + "\n"


def _append_section_lines(text: str, name: str, additions: object) -> str:
    if not isinstance(additions, list) or not all(
        isinstance(line, str) and "\n" not in line for line in additions
    ):
        raise MagicPexError(
            f"source_technology.section_extensions.{name} must be a list of single-line strings"
        )
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == name)
        end = next(
            i for i in range(start + 1, len(lines)) if lines[i].strip() == "end"
        )
    except StopIteration as exc:
        raise MagicPexError(
            f"technology base has no complete {name} section"
        ) from exc
    return "\n".join(
        lines[:end] + [f"    {line}" for line in additions] + lines[end:]
    ) + "\n"



_WELL_ROUTE_CONNECTS = {
    "nwell,nsc,nsd nwell,nsc,nsd",
    "pwell,psc,psd pwell,psc,psd",
}


def without_well_routing(technology: str) -> str:
    """Return a diagnostic technology with normal well routing disabled.

    This mirrors the archived ``scmosWR.tech`` behavior while preserving the
    active profile's layer map and generated extraction section.  Only the
    normal n-well and p-well self-connect rules are removed; high-voltage well
    rules and all non-well connectivity remain unchanged.
    """

    lines = technology.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "connect")
    except StopIteration as exc:
        raise MagicPexError("technology base has no connect section") from exc
    try:
        end = next(
            i for i in range(start + 1, len(lines)) if lines[i].strip() == "end"
        )
    except StopIteration as exc:
        raise MagicPexError("technology connect section has no end") from exc

    removed: set[str] = set()
    kept: list[str] = []
    for line in lines[start + 1 : end]:
        normalized = re.sub(r"\s+", " ", line.strip())
        if normalized in _WELL_ROUTE_CONNECTS:
            removed.add(normalized)
            continue
        kept.append(line)
    missing = _WELL_ROUTE_CONNECTS - removed
    if missing:
        raise MagicPexError(
            "technology connect section is missing normal well rules: "
            + ", ".join(sorted(missing))
        )
    return "\n".join(lines[: start + 1] + kept + lines[end:]) + "\n"


def _required(mapping: dict[str, Any], key: str, context: str) -> Any:
    value = mapping.get(key)
    if value is None or value == "":
        raise MagicPexError(f"{context} is missing {key}")
    return value


def _render_mosfet(spec: dict[str, Any], name: str) -> str:
    context = f"topology.devices.{name}"
    model = _required(spec, "model", context)
    fet_type = _required(spec, "fet_type", context)
    terminals = _required(spec, "terminal_types", context)
    substrate = _required(spec, "substrate_types", context)
    node = _required(spec, "substrate_node", context)
    gscap = spec.get("gscap_af_per_lambda", 0)
    gccap = spec.get("gccap_af_per_lambda2", 0)
    return (
        f"    device mosfet {model} {fet_type} {terminals} {substrate} "
        f"{node} {_integer(gscap)} {_integer(gccap)}"
    )


def _render_msubcircuit(spec: dict[str, Any], name: str) -> str:
    context = f"topology.devices.{name}"
    model = _required(spec, "model", context)
    gate_type = _required(spec, "gate_type", context)
    terminals = _required(spec, "terminal_types", context)
    disambiguator = _required(spec, "drain_disambiguator", context)
    substrate = _required(spec, "substrate_types", context)
    node = _required(spec, "substrate_node", context)
    minimum_terminals = spec.get("minimum_terminals", 2)
    params = spec.get("parameters", "w=W l=L p1=PD p2=PS")
    return (
        f"    device msubcircuit {model} {gate_type} {minimum_terminals} "
        f"{terminals} {terminals},{disambiguator} {substrate} {node} {params}"
    )


def _bound_topology_devices(
    topology: dict[str, Any], device_bindings: dict[str, Any] | None
) -> dict[str, Any]:
    devices = dict(topology.get("devices") or {})
    if not device_bindings:
        return devices
    if topology.get("magic_device_class") != "mosfet":
        return devices
    for polarity, binding_name in (("nmos", "nmos_core"), ("pmos", "pmos_core")):
        binding = device_bindings.get(binding_name)
        if binding is None:
            continue
        layout = getattr(binding, "layout", {}) or {}
        simulation = getattr(binding, "simulation", {}) or {}
        spec = dict(devices.get(polarity) or {})
        for key, value in (
            ("model", simulation.get("name")),
            ("fet_type", layout.get("gate_types")),
            ("terminal_types", layout.get("terminal_types")),
            ("substrate_types", layout.get("substrate_types")),
            ("substrate_node", layout.get("substrate_node")),
        ):
            if value is not None:
                spec[key] = value
        devices[polarity] = spec
    return devices


def render_topology(
    manifest: dict[str, Any], device_bindings: dict[str, Any] | None = None
) -> str:
    physical = _required(manifest, "physical", "manifest")
    topology = _required(manifest, "topology", "manifest")
    lam = _required(physical, "magic_lambda_centimicron", "physical")
    style = _required(topology, "style", "topology")
    lines = [
        "extract",
        f"  style {style}",
        f"    lambda {lam}",
        f"    cscale {topology.get('cscale', 1)}",
        f"    step {topology.get('step', 100)}",
        f"    sidehalo {topology.get('sidehalo', 0)}",
    ]
    plane_order = topology.get(
        "plane_order",
        [
            ["active", 0],
            ["well", 1],
            ["implant", 2],
            ["metal1", 3],
            ["metal2", 4],
            ["metal3", 5],
            ["oxide", 6],
        ],
    )
    for plane, order in plane_order:
        lines.append(f"    planeorder {plane} {order}")

    devices = _bound_topology_devices(topology, device_bindings)
    if devices:
        device_class = topology.get("magic_device_class", "mosfet")
        for name in ("nmos", "pmos"):
            spec = devices.get(name)
            if not spec:
                continue
            if device_class == "mosfet":
                lines.append(_render_mosfet(spec, name))
            elif device_class == "msubcircuit":
                lines.append(_render_msubcircuit(spec, name))
            else:
                raise MagicPexError(
                    f"unsupported Magic MOS device class {device_class!r}"
                )
    else:
        # Backward-compatible rendering of the original LS1u manifest.
        device_class = _required(topology, "magic_device_class", "topology")
        disambiguator = _required(
            topology, "magic_drain_disambiguator", "topology"
        )
        for name, polarity in (("nmos", "nmos"), ("pmos", "pmos")):
            model = _required(topology["models"], polarity, "topology.models")
            gate = _required(
                topology["gate_types"], polarity, "topology.gate_types"
            )
            terminals = _required(
                topology["terminal_types"], polarity, "topology.terminal_types"
            )
            substrate = _required(
                topology["substrate_types"], polarity, "topology.substrate_types"
            )
            node = _required(
                topology["substrate_nodes"], polarity, "topology.substrate_nodes"
            )
            if device_class != "msubcircuit":
                raise MagicPexError(
                    "legacy topology only supports magic_device_class=msubcircuit"
                )
            lines.append(
                f"    device msubcircuit {model} {gate} 2 {terminals} "
                f"{terminals},{disambiguator} {substrate} {node} "
                "w=W l=L p1=PD p2=PS"
            )
    return "\n".join(lines + ["end", ""])


def _render_structured_directive(item: dict[str, Any], lambda_um: object) -> str:
    kind = _required(item, "kind", "magic_directives item")
    if kind == "raw":
        return "    " + str(_required(item, "text", "raw directive"))
    if kind == "fetresis":
        return "    " + " ".join(
            [
                "fetresis",
                str(_required(item, "device", "fetresis directive")),
                str(_required(item, "regime", "fetresis directive")),
                str(_required(item, "value", "fetresis directive")),
            ]
        )

    value = _required(item, "value", str(kind))
    unit = _required(item, "unit", str(kind))
    converted = (
        capacitance_to_magic(value, unit, lambda_um)
        if kind in {"areacap", "perimc", "overlap", "sideoverlap", "sidewall"}
        else convert_to_magic(value, unit, lambda_um)
    )
    if kind == "resist":
        return f"    resist {_required(item, 'layers', kind)} {converted}"
    if kind == "areacap":
        return f"    areacap {_required(item, 'layers', kind)} {converted}"
    if kind == "perimc":
        return (
            f"    perimc {_required(item, 'layers', kind)} "
            f"{_required(item, 'outside', kind)} {converted}"
        )
    if kind == "overlap":
        fields = [
            "overlap",
            str(_required(item, "upper", kind)),
            str(_required(item, "lower", kind)),
            str(converted),
        ]
        if item.get("shield"):
            fields.append(str(item["shield"]))
        return "    " + " ".join(fields)
    if kind == "sideoverlap":
        fields = [
            "sideoverlap",
            str(_required(item, "upper", kind)),
            str(_required(item, "edge", kind)),
            str(_required(item, "lower", kind)),
            str(converted),
        ]
        if item.get("shield"):
            fields.append(str(item["shield"]))
        return "    " + " ".join(fields)
    if kind == "sidewall":
        fields = [
            "sidewall",
            str(_required(item, "upper", kind)),
            str(_required(item, "outside_upper", kind)),
            str(_required(item, "outside_lower", kind)),
            str(_required(item, "lower", kind)),
            str(converted),
        ]
        return "    " + " ".join(fields)
    if kind == "contact":
        contact_type = _required(item, "contact_type", kind)
        min_size = _required(item, "min_size", kind)
        return f"    contact {contact_type} {min_size} {converted}"
    raise MagicPexError(f"unsupported Magic directive kind {kind!r}")


def _render_legacy_directives(
    spec: dict[str, Any], physical: dict[str, Any], manifest: dict[str, Any]
) -> list[str]:
    directives: list[str] = []
    for layer in ("metal1", "metal2", "metal3"):
        value = (spec.get("metal_sheet_resistance_ohm_sq") or {}).get(layer)
        if value is not None:
            directives.append(
                f"    resist {layer} "
                f"{convert_to_magic(value, 'ohm_per_square', physical['lambda_um'])}"
            )
    legacy = list(spec.get("legacy_directives") or [])
    directives.extend(f"    {directive}" for directive in legacy)
    for pair, value in (spec.get("overlap_capacitance_ff_per_um2") or {}).items():
        if value is None:
            continue
        lower, upper = pair.split("_", 1)
        cap = convert_to_magic(value, "ff_per_um2", physical["lambda_um"])
        directives.append(f"    overlap {upper} {lower} {cap}")
    native = bool(
        (manifest.get("flow") or {}).get("legacy_directives_are_magic_native")
    )
    for key, value in (spec.get("contact_resistance_mohm") or {}).items():
        if value is not None and not native:
            raise MagicPexError(
                f"contact '{key}' needs an explicit Magic contact mapping"
            )
    for key, value in (spec.get("via_resistance_mohm") or {}).items():
        if value is not None and not native:
            raise MagicPexError(f"via '{key}' needs an explicit Magic contact mapping")
    return directives


def render_profile_extract(
    manifest: dict[str, Any],
    profile_name: str,
    device_bindings: dict[str, Any] | None = None,
) -> str:
    physical = _required(manifest, "physical", "manifest")
    profiles = _required(manifest, "profiles", "manifest")
    spec = profiles.get(profile_name)
    if not isinstance(spec, dict):
        raise MagicPexError(f"unknown PEX profile {profile_name!r}")
    lines = render_topology(manifest, device_bindings).rstrip("\n").splitlines()
    directives: list[str] = []
    if spec.get("magic_directives"):
        for item in spec["magic_directives"]:
            if not isinstance(item, dict):
                raise MagicPexError("magic_directives entries must be mappings")
            source = item.get("source")
            if source:
                directives.append("    # " + " ".join(str(source).split()))
            directives.append(
                _render_structured_directive(item, physical["lambda_um"])
            )
    else:
        directives.extend(_render_legacy_directives(spec, physical, manifest))
    if spec.get("maturity") == "estimated":
        directives.insert(
            0,
            "    # WARNING: estimated parasitic coefficients; not foundry signoff.",
        )
    insert_at = len(lines) - 1
    return "\n".join(lines[:insert_at] + directives + lines[insert_at:] + [""])


def _replace_description(text: str, description: object) -> str:
    if description is None:
        return text
    pattern = r'(\sdescription\s+)"[^"]*"'
    replacement = lambda match: match.group(1) + '"' + str(description) + '"'
    updated, count = re.subn(pattern, replacement, text, count=1)
    if count == 0:
        raise MagicPexError("technology base has no version description")
    return updated


def _validate_legacy_backend(manifest: dict[str, Any]) -> None:
    source = manifest.get("source_technology") or {}
    legacy = source.get("legacy_backend")
    if legacy is None:
        return
    if not isinstance(legacy, dict):
        raise MagicPexError("source_technology.legacy_backend must be a mapping")
    actual_lambda = _decimal(
        _required(manifest.get("physical") or {}, "lambda_um", "physical")
    )
    expected_lambda = _decimal(
        _required(legacy, "expected_lambda_um", "legacy_backend")
    )
    if actual_lambda != expected_lambda:
        raise MagicPexError(
            "legacy backend lambda does not match physical.lambda_um: "
            f"{expected_lambda} != {actual_lambda}"
        )
    expected_technology = {
        Decimal("0.3"): "scmos-sub",
        Decimal("0.8"): "scmos",
    }.get(expected_lambda)
    selected_technology = str(_required(legacy, "technology", "legacy_backend"))
    if expected_technology and selected_technology != expected_technology:
        raise MagicPexError(
            f"lambda {expected_lambda} requires legacy backend "
            f"{expected_technology!r}, got {selected_technology!r}"
        )
    _required(legacy, "extraction_style", "legacy_backend")


def assemble_technology(
    manifest: dict[str, Any],
    profile_name: str,
    manifest_dir: Path,
    device_bindings: dict[str, Any] | None = None,
) -> str:
    _validate_legacy_backend(manifest)
    source = _required(manifest, "source_technology", "manifest")
    base_path = (manifest_dir / _required(source, "file", "source_technology")).resolve()
    map_path = (
        manifest_dir / _required(source, "gds_input_map", "source_technology")
    ).resolve()
    if not base_path.exists():
        raise MagicPexError(f"Magic base technology not found: {base_path}")
    if not map_path.exists():
        raise MagicPexError(f"Magic GDS input map not found: {map_path}")
    assembled = base_path.read_text()
    assembled = _replace_description(
        assembled, manifest.get("technology", {}).get("description")
    )
    extensions = source.get("section_extensions") or {}
    if not isinstance(extensions, dict):
        raise MagicPexError(
            "source_technology.section_extensions must be a mapping"
        )
    for name, additions in extensions.items():
        if not isinstance(name, str) or name in {"cifinput", "extract"}:
            raise MagicPexError(
                "section_extensions may only extend non-generated sections"
            )
        assembled = _append_section_lines(assembled, name, additions)
    cif = map_path.read_text().rstrip("\n")
    cif_lines = cif.splitlines()
    if cif_lines and cif_lines[0].strip() == "cifinput":
        cif = "\n".join(cif_lines[1:])
    extract = render_profile_extract(manifest, profile_name, device_bindings).rstrip("\n")
    assembled = _replace_section(assembled, "cifinput", "cifinput\n" + cif)
    return _replace_section(assembled, "extract", extract)


def generate_profile(
    manifest: dict[str, Any],
    manifest_path: Path,
    profile_name: str,
    device_bindings: dict[str, Any] | None = None,
) -> Path:
    spec = manifest.get("profiles", {}).get(profile_name)
    if not isinstance(spec, dict):
        raise MagicPexError(f"unknown PEX profile {profile_name!r}")
    if spec.get("generated") is False:
        raise MagicPexError(f"profile {profile_name} is reserved and not generated")
    configured_output = spec.get("output")
    output_name = (
        configured_output
        if isinstance(configured_output, str)
        else f"{profile_name}.tech"
    )
    output = manifest_path.parent / output_name
    output.write_text(
        assemble_technology(manifest, profile_name, manifest_path.parent, device_bindings)
    )
    return output


def topology_fragment(
    manifest: dict[str, Any], device_bindings: dict[str, Any] | None = None
) -> str:
    return (
        GENERATED_PREFIX
        + "\n"
        + "/* Standalone extract section generated from the process manifest. */\n"
        + render_topology(manifest, device_bindings)
    )