#!/usr/bin/env python3
"""Generate the authoritative LVS deck for a profile from its devices.yaml.

Validates profiles/<proc>/devices.yaml (kind tables with required fields)
and writes profiles/<proc>/generated/lvs/run.py — the deck that
scripts/run_lvs.py --deck authoritative executes.

Usage:
  python3 scripts/gen_lvs.py --profile ams_c35 --variant C35B4C3
"""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from common.process_ir import load_process  # noqa: E402
KIND_KEYS = {
    "mos4": ("name", "channel", "diff", "bulk_net"),
    "ldmos": (
        "name",
        "channel",
        "source_diff",
        "drain_diff",
        "bulk_net",
    ),
    "resistor": ("name", "body", "sheet"),
    "capacitor": ("name", "region", "top", "bottom", "area_cap"),
    "diode": ("name", "region", "plus", "minus"),
    "jfet": ("name", "region"),
    "npn": ("name", "region", "collector", "base", "emitter"),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", required=True)
    ap.add_argument("--variant", default=None, help="select a profile module variant")
    args = ap.parse_args()

    process = load_process(args.profile, ROOT, variant=args.variant)
    profile_dir = process.profile_dir
    devices_path = profile_dir / "devices.yaml"
    if not devices_path.exists():
        raise SystemExit(f"no devices.yaml in {profile_dir}")
    devices = process.devices_doc
    engine = devices.get("engine", "scmos_authoritative")
    if engine != "scmos_authoritative":
        raise SystemExit(
            f"{devices_path}: engine={engine!r} is not supported by the SCMOS "
            "authoritative generator; use the profile reference deck or add "
            "a process-specific generator"
        )
    kinds = devices.get("devices", {})
    if not kinds:
        raise SystemExit(f"{devices_path}: missing 'devices' section")
    n = 0
    for kind, entries in kinds.items():
        if kind not in KIND_KEYS:
            raise SystemExit(f"{devices_path}: unknown device kind '{kind}'")
        for entry in entries:
            missing = [req for req in KIND_KEYS[kind] if req not in entry]
            if kind in {"mos4", "ldmos", "diode"} and not any(
                entry.get(key) for key in ("model_suffix", "model_name")
            ):
                missing.append("model_suffix or model_name")
            if kind == "resistor":
                if entry.get("terminal_marker"):
                    if "terminal_layer" not in entry:
                        missing.append("terminal_layer")
                elif "conn" not in entry:
                    missing.append("conn or terminal_marker")
            if missing:
                raise SystemExit(
                    f"{devices_path} [{kind}]: entry missing {', '.join(missing)}: {entry}"
                )
            n += 1
    process_variant = process.process_variant or ""
    deck = f"""# Generated by scripts/gen_lvs.py from {devices_path.relative_to(ROOT)} — DO NOT HAND-EDIT.
# Regenerate with: python3 scripts/gen_lvs.py --profile {args.profile}
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(_ROOT, "common", "lvs"))
os.environ.setdefault("PROCESS_VARIANT", {process_variant!r})
from scmos_authoritative_lvs import run

run()
"""
    out = profile_dir / "generated" / "lvs" / "run.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(deck)
    print(f"wrote {out}: {n} device definitions from {devices_path.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
