#!/usr/bin/env python3
"""Generate the authoritative DRC deck for a profile from its rules.yaml.

Validates profiles/<proc>/rules.yaml and writes the selected authority deck.
The default SCMOS compatibility deck is generated as run.py.  Named
public/foundry decks also retain a .drc artifact for release naming and emit a
.py companion because KLayout interprets .drc files as Ruby macros.

Usage:
  python3 scripts/gen_drc.py --profile ami06
  python3 scripts/gen_drc.py --profile xh035 --authority public_native

"""
import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from common.process_ir import load_process  # noqa: E402
TABLES = ("width", "spacing", "enclosure", "extension", "area", "notch", "overlap")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", required=True)
    ap.add_argument(
        "--authority",
        choices=("public_native", "scmos_compat", "foundry_private"),
        default="scmos_compat",
        help="rule authority layer selected by the generated deck",
    )
    ap.add_argument(
        "--output",
        default=None,
        help="optional generated deck path; defaults to profile-specific run.py/name",
    )
    args = ap.parse_args()

    process = load_process(args.profile, ROOT)
    profile_dir = process.profile_dir
    rules_path = profile_dir / "rules.yaml"
    if not rules_path.exists():
        raise SystemExit(f"no rules.yaml in {profile_dir}")
    rules = process.rules_doc
    engine = rules.get("engine", "scmos_authoritative")
    if engine != "scmos_authoritative":
        raise SystemExit(
            f"{rules_path}: engine={engine!r} is not supported by the SCMOS "
            "authoritative generator; use the profile reference deck or add "
            "a process-specific generator"
        )
    tables = rules.get("rules", {})
    if not tables:
        raise SystemExit(f"{rules_path}: missing 'rules' section")

    n = 0
    for table in TABLES:
        for entry in tables.get(table, []):
            for req in ("id", "layer", "value_um"):
                if req not in entry:
                    raise SystemExit(f"{rules_path} [{table}]: entry missing '{req}': {entry}")
            n += 1

    deck = f"""# Generated by scripts/gen_drc.py from {rules_path.relative_to(ROOT)} — DO NOT HAND-EDIT.
# Regenerate with: python3 scripts/gen_drc.py --profile {args.profile} --authority {args.authority}
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(_ROOT, "common", "drc"))
os.environ.setdefault("RULES", os.path.join(_HERE, "..", "..", "rules.yaml"))
os.environ["RULE_AUTHORITY"] = "{args.authority}"
from scmos_authoritative import run

run()
"""
    if args.output:
        out = Path(args.output)
        if not out.is_absolute():
            out = ROOT / out
    elif args.authority == "scmos_compat":
        out = profile_dir / "generated" / "drc" / "run.py"
    else:
        suffix = {
            "public_native": "public",
            "foundry_private": "foundry-private",
        }[args.authority]
        out = profile_dir / "generated" / "drc" / f"{args.profile}-{suffix}.drc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(deck)
    runtime_out = None
    if out.suffix == ".drc":
        # KLayout treats .drc as Ruby.  Keep the requested named artifact and
        # emit a .py companion for this Python/pya deck.
        runtime_out = out.with_suffix(".py")
        runtime_out.write_text(deck)
    suffix = f"; runtime={runtime_out}" if runtime_out else ""
    print(f"wrote {out}: {n} rules from {rules_path.relative_to(ROOT)}{suffix}")


if __name__ == "__main__":
    sys.exit(main())
