#!/usr/bin/env python3
"""Generate profiles/<proc>/models/<proc>.lib for ngspice.

Assembles the public BSIM3v3 model cards from the NCSU CDK tree
(models/hspice/public/publicModel/ for the nom corner) into the profile's
model library.  Corner sections (ss/ff/fnsp/snfp) are added when the CDK
tree ships them for the process (the TSMC/HP processes do; ami06 does not —
its corners are NDA/absent, noted in the generated file).

Usage:
  python3 scripts/gen_models.py --profile <proc> [--cdk ../ncsu-cdk-1.6.0]
"""

import argparse
import re
import sys
from pathlib import Path

LS1U_PMOS_VTH0 = -0.6
LS1U_PMOS_U0 = 83.0

ROOT = Path(__file__).resolve().parent.parent
CORNER_DIRS = {"nom": "nom", "slow": "slow", "fast": "fast",
               "fnsp": "fnsp", "snfp": "snfp"}
def apply_ls1u_pmos_fit(card):
    """Apply the explicitly recorded low-confidence HKUST PMOS fit."""
    start = card.index(".MODEL PMOS")
    end = card.index(")", start)
    block = card[start:end]
    block = re.sub(r"(?m)^\+ U0\s*=.*$", f"+ U0      = {LS1U_PMOS_U0}", block)
    block = re.sub(r"(?m)^\+ VTH0\s*=.*$", f"+ VTH0    = {LS1U_PMOS_VTH0}", block)
    return card[:start] + block + card[end:]




def generate_ls1u():
    profile_dir = ROOT / "profiles" / "ls1u"
    reference_dir = profile_dir / "reference"
    model_dir = profile_dir / "models"
    model_dir.mkdir(parents=True, exist_ok=True)
    nmos_path = reference_dir / "nmos1u.lib"
    pmos_path = reference_dir / "pmos1u.lib"
    if not nmos_path.exists() or not pmos_path.exists():
        raise SystemExit(
            f"LS1u model sources missing under {reference_dir} "
            "(expected nmos1u.lib and pmos1u.lib)"
        )
    nmos = nmos_path.read_text().strip()
    pmos = apply_ls1u_pmos_fit(pmos_path.read_text().strip())
    nmos = nmos.replace(".ENDS LV1UPMOS", ".ENDS LV1UNMOS")
    out = model_dir / "ls1u.lib"
    lines = [
        "* profiles/ls1u/models/ls1u.lib — generated by scripts/gen_models.py",
        "* source: LibreSilicon process repository simulation/nmos1u.lib and",
        "*         simulation/pmos1u.lib at the profile manifest commit",
        "* normalization: corrected the upstream NMOS .ENDS subcircuit name",
        "* empirical PMOS fit: VTH0=-0.6 V, U0=83 cm^2/V/s",
        "* fit source: supplied thermally_compensated.ods; L10/W10; low confidence",
        "* fit window: corrected Id_residue, VSG=1.5..5 V, VDS=-0.5 V",
        "* caveat: NGATE/PGATE remain unmeasured in the upstream cards",
        ".lib ls1u",
        "",
        nmos,
        "",
        pmos,
        "",
        ".endl ls1u",
        "",
    ]
    out.write_text("\n".join(lines))
    print(f"wrote {out}: sections ['ls1u']")
    return 0


def model_prefix_for(profile: str) -> str:
    """Return the CDK card prefix recorded by the normalized layer profile."""
    layers = ROOT / "profiles" / profile / "layers.yaml"
    if layers.exists():
        for line in layers.read_text().splitlines():
            if line.strip().startswith("model_prefix:"):
                return line.split(":", 1)[1].strip().strip('"')
    return profile

def normalize_hspice_card(text: str) -> str:
    """Remove HSPICE library wrappers before nesting cards in ngspice .lib."""
    lines = []
    for line in text.splitlines():
        token = line.strip().upper()
        if token.startswith(".LIB ") or token.startswith(".ENDL ") or token == ".END":
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", required=True)
    ap.add_argument("--cdk", default="../ncsu-cdk-1.6.0")
    args = ap.parse_args()
    if args.profile == "ls1u":
        return generate_ls1u()

    cdk = Path(args.cdk)
    pub = cdk / "models/hspice/public/publicModel"
    if not pub.exists():
        raise SystemExit(f"public model dir not found: {pub}")
    prefix = model_prefix_for(args.profile)
    model_dir = ROOT / "profiles" / args.profile / "models"
    model_dir.mkdir(parents=True, exist_ok=True)
    out = model_dir / f"{args.profile}.lib"

    # nom cards from the public HSPICE cards
    cards = {}
    for dev in ("N", "P"):
        p = pub / f"{prefix}{dev}"
        if not p.exists():
            raise SystemExit(f"missing public card {p}")
        cards[dev] = normalize_hspice_card(p.read_text())

    lines = [f"* profiles/{args.profile}/models/{args.profile}.lib — generated by scripts/gen_models.py",
             f"* source: NCSU CDK 1.6.0 {pub.relative_to(cdk)} (public MOSIS BSIM3v3 cards)",
             f"* prefix: {prefix}  (model names: {prefix}N, {prefix}P — match the LVS extractor)",
             f"* corners: {sorted(CORNER_DIRS)} — only 'nom' is public for this process;",
             "*          ss/ff/fnsp/snfp sections are emitted only if the CDK ships them.",
             f"* usage:  .lib '<path>/{args.profile}.lib' {args.profile}",
             ""]

    sections = [(args.profile, "nom")]
    for corner, d in CORNER_DIRS.items():
        src = cdk / "models/hspice" / d
        if (src / f"{prefix}N").exists() and (src / f"{prefix}P").exists():
            sections.append((corner, d))

    for sec_name, d in sections:
        lines.append(f".lib {sec_name}")
        if d == "nom":
            lines += [cards["N"], cards["P"]]
        else:
            src = cdk / "models/hspice" / d
            lines.append(f"* corner cards from {src.relative_to(cdk)}")
            for dev in ("N", "P"):
                card = normalize_hspice_card((src / f"{prefix}{dev}").read_text())
                lines.append(card)
        lines.append(f".endl {sec_name}")
        lines.append("")
    lines.append(".end")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: sections {[s for s, _ in sections]}")


if __name__ == "__main__":
    sys.exit(main())
