#!/usr/bin/env python3
"""Generate the xschem symbol library for a profile from symbols.yaml.

Emits profiles/<proc>/generated/xschem/<sym>.sym + xschemrc (library search
paths).  FET geometry follows the Apache-2.0 xschem_sky130 symbol style
(attribution kept); pin boxes and template attributes come from the YAML.

Usage:
  python3 scripts/gen_symbols.py --profile ami06
"""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from common.devices.netlist import netlist_contract  # noqa: E402
from common.process_ir import load_process  # noqa: E402

HEADER = """v {xschem version=3.4.7 file_version=1.2
* Generated by scripts/gen_symbols.py from profiles/@PROFILE@/symbols.yaml — DO NOT HAND-EDIT.
* FET geometry style: (c) 2021 Stefan Frederik Schippers, xschem_sky130,
* Apache License 2.0 — https://github.com/StefanSchippers/xschem_sky130
}
G {}
K {type=@TYPE@
@PREFIX@@GLOBAL@format="@FMT@"
@LVS@template="@TMPL@"
}
V {}
S {}
E {}
"""

FET_BODY = """L 4 7.5 -22.5 7.5 22.5 {}
L 4 -20 0 2.5 0 {}
L 4 20 -30 20 -17.5 {}
L 4 20 17.5 20 30 {}
L 4 2.5 -15 2.5 15 {}
L 4 7.5 -17.5 20 -17.5 {}
L 4 7.5 17.5 15 17.5 {}
P 4 4 15 15 20 17.5 15 20 15 15 {fill=true}
P 5 4 20 -2.5 15 0 20 2.5 20 -2.5 {fill=true}
"""

PMOS_GATE = """L 4 -20 0 -12.5 0 {}
L 4 -12.5 0 -10 5 {}
L 4 -10 5 -5 -5 {}
L 4 -5 -5 0 0 {}
L 4 0 0 2.5 0 {}
"""

NMOS_GATE = """L 4 -20 0 2.5 0 {}
"""


def emit_fet(entry):
    body = FET_BODY + (PMOS_GATE if entry["type"] == "pmos" else NMOS_GATE)
    return body


def emit_two_pin(entry):
    kind = entry.get("shape", entry["type"])
    if kind == "res":
        return ("L 4 -7.5 0 -2.5 0 {}\n"
                "L 4 -2.5 0 -1.25 3.75 {}\n"
                "L 4 -1.25 3.75 1.25 -3.75 {}\n"
                "L 4 1.25 -3.75 2.5 0 {}\n"
                "L 4 2.5 0 7.5 0 {}\n")
    if kind == "cap":
        return ("L 4 -7.5 0 -2.5 0 {}\n"
                "L 4 -2.5 -7.5 -2.5 7.5 {}\n"
                "L 4 2.5 -7.5 2.5 7.5 {}\n"
                "L 4 2.5 0 7.5 0 {}\n")
    # diode
    return ("L 4 -7.5 0 -2.5 0 {}\n"
            "L 4 -2.5 -6.25 -2.5 6.25 {}\n"
            "L 4 -2.5 6.25 4.5 0 {}\n"
            "L 4 -2.5 -6.25 4.5 0 {}\n"
            "L 4 2.5 -5 2.5 5 {}\n"
            "L 4 2.5 0 7.5 0 {}\n")


def emit_src(entry):
    return ("A 4 0 0 30 0 360 {}\n"
            "L 4 -30 0 -15 0 {}\n"
            "L 4 15 0 30 0 {}\n")


def emit_lab_pin(entry):
    return ("L 4 0 0 8 0 {}\n"
            "L 4 8 0 4 2.5 {}\n"
            "L 4 8 0 4 -2.5 {}\n")


def emit_gnd(entry):
    return ("L 4 0 0 0 10 {}\n"
            "L 4 -10 10 10 10 {}\n"
            "L 4 -5 15 5 15 {}\n"
            "L 4 -1.5 19 1.5 19 {}\n")


def template_string(template):
    fields = []
    for key, value in template.items():
        text = str(value)
        if " " in text:
            text = r'\\"' + text + r'\\"'
        fields.append(f"{key}={text}")
    return " ".join(fields)


def gen(profile_dir, sym_name, ui_entry, netlist_entry, contract=None):
    entry = dict(ui_entry)
    entry.update(netlist_entry)
    if contract is not None:
        entry.setdefault("spiceprefix", contract.prefix)
        template = dict(entry.get("template") or {})
        template.setdefault("model", contract.name)
        entry["template"] = template
    pins = entry["pins"]
    template = entry["template"]
    fmt = entry["format"]
    global_line = "global=true\n" if entry.get("global") else ""
    tmpl = template_string(template)
    lvs_line = (
        f"lvs_format=\"{entry['lvs_format']}\"\n"
        if entry.get("lvs_format")
        else ""
    )
    prefix = (
        f"spiceprefix={entry['spiceprefix']}\n"
        if entry.get("spiceprefix")
        else ""
    )
    lines = [HEADER.replace("@PROFILE@", profile_dir.name)
                   .replace("@TYPE@", entry["type"])
                   .replace("@PREFIX@", prefix)
                   .replace("@GLOBAL@", global_line)
                   .replace("@LVS@", lvs_line)
                   .replace("@FMT@", fmt)
                   .replace("@TMPL@", tmpl)]
    kind = entry["kind"]
    if kind == "fet":
        lines.append(emit_fet(entry))
    elif kind == "two_pin":
        lines.append(emit_two_pin(entry))
    elif kind == "src":
        lines.append(emit_src(entry))
    elif kind == "gnd":
        lines.append(emit_gnd(entry))
    elif kind == "lab_pin":
        lines.append(emit_lab_pin(entry))
    for pin in pins:
        goto = " goto=0" if kind == "gnd" else ""
        lines.append(
            f"B 5 {pin['x1']} {pin['y1']} {pin['x2']} {pin['y2']} "
            f"{{name={pin['name']} dir={pin['dir']}{goto}}}")
    for pin in pins:
        if pin["name"] in ("0",):
            continue
        cx = (pin["x1"] + pin["x2"]) / 2
        cy = (pin["y1"] + pin["y2"]) / 2
        lines.append(f"T {{{pin['name'].upper()}}} {cx + 3} {cy} 0 0 0.15 0.15 {{}}")
    lines.append(f"T {{@name}} -10 -40 0 1 0.2 0.2 {{}}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", required=True)
    args = ap.parse_args()

    process = load_process(args.profile, ROOT)
    profile_dir = process.profile_dir
    symbols_path = profile_dir / "symbols.yaml"
    if not symbols_path.exists():
        raise SystemExit(f"no symbols.yaml in {profile_dir}")
    table = process.symbols
    netlist_table = process.symbol_netlist
    if not table:
        raise SystemExit(f"{symbols_path}: missing 'symbols' section")

    out_dir = profile_dir / "generated" / "xschem"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, entry in table.items():
        netlist_entry = netlist_table.get(name)
        if not isinstance(netlist_entry, dict):
            raise SystemExit(
                f"{profile_dir}/devices/symbol_netlist.yaml: missing binding for {name}"
            )
        binding_name = netlist_entry.get("device_binding")
        contract = (
            netlist_contract(process, str(binding_name))
            if binding_name
            else None
        )
        (out_dir / f"{name}.sym").write_text(
            gen(profile_dir, name, entry, netlist_entry, contract)
        )

    rc = out_dir / "xschemrc"
    rc.write_text(
        f"# xschemrc for siliconcraft {args.profile} (generated) — DO NOT HAND-EDIT.\n"
        f"set XSCHEM_START_WINDOW 1\n"
        f"set XSCHEM_LIBRARY_PATH {{ {out_dir.resolve()} }}\n"
        f"set XSCHEM_DESIGN_DIR {profile_dir.resolve()}\n")
    print(f"wrote {len(table)} symbols + xschemrc to {out_dir}")


if __name__ == "__main__":
    sys.exit(main())