#!/usr/bin/env python3
"""Generate the authoritative DRC deck for a profile from its rules.yaml.

Validates profiles/<proc>/rules.yaml (schema: id/layer/value_um per entry,
known tables) and writes profiles/<proc>/generated/drc/run.drc — the deck
that scripts/run_drc.py --deck authoritative executes.

Usage:
  python3 scripts/gen_drc.py --profile ami06
"""

import argparse
import sys
from pathlib import Path

import yamlish

ROOT = Path(__file__).resolve().parent.parent
TABLES = ("width", "spacing", "enclosure", "extension", "area", "notch", "overlap")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", required=True)
    args = ap.parse_args()

    profile_dir = ROOT / "profiles" / args.profile
    rules_path = profile_dir / "rules.yaml"
    if not rules_path.exists():
        raise SystemExit(f"no rules.yaml in {profile_dir}")
    rules = yamlish.load(rules_path.read_text())
    engine = rules.get("engine", "scmos_authoritative")
    if engine != "scmos_authoritative":
        raise SystemExit(
            f"{rules_path}: engine={engine!r} is not supported by the SCMOS "
            "authoritative generator; use the profile reference deck or add "
            "a process-specific generator"
        )
    tables = rules.get("rules", {})
    if not tables:
        raise SystemExit(f"{rules_path}: missing 'rules' section")

    n = 0
    for table in TABLES:
        for entry in tables.get(table, []):
            for req in ("id", "layer", "value_um"):
                if req not in entry:
                    raise SystemExit(f"{rules_path} [{table}]: entry missing '{req}': {entry}")
            n += 1

    deck = f"""# Generated by scripts/gen_drc.py from {rules_path.relative_to(ROOT)} — DO NOT HAND-EDIT.
# Regenerate with: python3 scripts/gen_drc.py --profile {args.profile}
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(_ROOT, "common", "drc"))
os.environ.setdefault("RULES", os.path.join(_HERE, "..", "..", "rules.yaml"))
from scmos_authoritative import run

run()
"""
    out = profile_dir / "generated" / "drc" / "run.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(deck)
    print(f"wrote {out}: {n} rules from {rules_path.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
