#!/usr/bin/env python3
"""CNM25 GDS -> EM field-solver preparation (FastCap / FastHenry).

The APDK field-solver flow (Glade + FastCap) extracts 3D parasitic
CAPACITANCE from the layout; it does not extract resistance (the 2D deck is
parallel-plate C only, and FastCap is a pure capacitance solver).  This
script prepares both next-stage inputs from a CNM25 GDS:

  * FastCap input (.lst): net conductors + cross-section from cnm25.tch
    (METAL h=1.0 t=1.0, VIA h=2.0 t=0.8, METAL2 h=2.8 t=1.1 um) so the C
    field solve can run out of the box;
  * FastHenry input (.lst): filaments from orthogonal rectangle
    decomposition of the routing polygons, with vertical via segments, for
    R/L extraction.

The script only converts geometry — it never invokes fastcap/fasthenry (both
must be built separately; see docs/cnm25_em_flow.md).

Usage:
  python3 scripts/run_cnm25_em.py --layout in.gds --workdir build/em
      [--top-cell TOP] [--meshn 2] [--meshw 2]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# CNM25 conductor cross section (apdk glade/cnm25.tch "Fastcap conductor data")
# (height = bottom z, thickness = conductor height, both in um)
CONDUCTORS = {
    "METAL":  {"gds": (7, 0), "height": 1.000, "thickness": 1.000},
    "VIA":    {"gds": (10, 0), "height": 2.000, "thickness": 0.800},
    "METAL2": {"gds": (9, 0), "height": 2.800, "thickness": 1.100},
}
LABEL_GDS = (64, 0)
BULK_NODE = "vss"  # APDK FastCap bulk/ref node convention


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--layout", required=True)
    ap.add_argument("--workdir", default="build/em")
    ap.add_argument("--top-cell", default=None)
    ap.add_argument("--meshn", type=int, default=2)
    ap.add_argument("--meshw", type=int, default=2)
    args = ap.parse_args()

    import pya  # noqa: PLC0415 (klayout python package)

    layout = pya.Layout()
    layout.read(args.layout)
    top = layout.top_cell() if not args.top_cell else layout.cell(args.top_cell)
    if top is None:
        raise SystemExit(f"top cell not found: {args.top_cell or layout.top_cell().name}")

    # net labels on the text layer
    labels = {}  # (layer, poly index) -> net name
    tidx = layout.find_layer(LABEL_GDS[0], LABEL_GDS[1])
    if tidx is None:
        print("warning: no text layer (64,0) — nets will be unnamed", file=sys.stderr)

    def polys(layer_num: int, dtyp: int):
        idx = layout.find_layer(layer_num, dtyp)
        if idx is None:
            return []
        return list(top.shapes(idx).each())

    # collect per-net polygons with labels; a net is a label name, and every
    # polygon carrying that label (or the whole layer when unlabeled) becomes
    # one conductor set
    nets: dict[str, dict[str, list]] = {}
    for name, spec in CONDUCTORS.items():
        gds_layer, dtyp = spec["gds"]
        for shp in polys(gds_layer, dtyp):
            if not (shp.is_polygon() or shp.is_box()):
                continue
            poly = shp.polygon if shp.is_polygon() else pya.Polygon(shp.box)
            net = None
            if tidx is not None:
                for tshp in top.shapes(tidx).each():
                    if tshp.is_text():
                        t = tshp.text
                        if poly.inside(t.trans.disp):
                            net = t.string
                            break
            net = net or f"{name}_auto{len(nets)}"
            nets.setdefault(net, {}).setdefault(name, []).append(poly)

    out = Path(args.workdir)
    out.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------ FastCap
    fastcap = ["* CNM25 FastCap input — generated by scripts/run_cnm25_em.py",
               "* conductors per net; bulk/ref node: " + BULK_NODE]
    for net in sorted(nets):
        fastcap.append(f"C {net}")
        for name, polys_ in sorted(nets[net].items()):
            spec = CONDUCTORS[name]
            for poly in polys_:
                fastcap.append(
                    f"G {name.lower()} rectangular "
                    f"x1=0 y1=0 x2={poly.bbox().width() * layout.dbu:.4f} "
                    f"y2={poly.bbox().height() * layout.dbu:.4f} "
                    f"z={spec['height']:.4f} t={spec['thickness']:.4f}"
                )
        fastcap.append(f"Q {net}")
        fastcap.append("")
    fastcap.append(".end")
    fc_path = out / "cnm25_caps.lst"
    fc_path.write_text("\n".join(fastcap) + "\n")

    # ---------------------------------------------------------- FastHenry
    fh = ["* CNM25 FastHenry input — generated by scripts/run_cnm25_em.py",
          "* filament R/L extraction; um units",
          ".units um",
          f".default nhinc={args.meshn} nwinc={args.meshw}"]
    for net in sorted(nets):
        fh.append(f"* net {net}")
        for name, polys_ in sorted(nets[net].items()):
            spec = CONDUCTORS[name]
            if name == "VIA":
                for poly in polys_:
                    w = poly.bbox().width() * layout.dbu
                    h = poly.bbox().height() * layout.dbu
                    fh.append(
                        f"N{net}_via_{len(fh)} x=0 y=0 z={spec['height']:.4f}")
                    fh.append(
                        f"N{net}_via_{len(fh)}b x=0 y=0 z={spec['height'] + spec['thickness']:.4f}")
                    fh.append(
                        f"E {net}_via_{len(fh)} {net}_via_{len(fh)}b w={max(w, h):.4f} "
                        f"h={spec['thickness']:.4f} nhinc={args.meshn} nwinc={args.meshw}")
                continue
            for poly in polys_:
                # rectangle decomposition of the orthogonal polygon
                for rect in pya.Region(poly).rectangles():
                    b = rect.bbox()
                    w = b.width() * layout.dbu
                    h = b.height() * layout.dbu
                    if w <= 0 or h <= 0:
                        continue
                    # segment along the longer axis
                    seglen, segw = (w, h) if w >= h else (h, w)
                    fh.append(
                        f"N{net}_{name}_{len(fh)}a x=0 y=0 z={spec['height']:.4f}")
                    fh.append(
                        f"N{net}_{name}_{len(fh)}b x={seglen:.4f} y=0 "
                        f"z={spec['height']:.4f}")
                    fh.append(
                        f"E {net}_{name}_{len(fh)}a {net}_{name}_{len(fh)}b "
                        f"w={seglen:.4f} h={spec['thickness']:.4f} "
                        f"nhinc={args.meshn} nwinc={args.meshw}")
    fh.append(".freq fmin=1e6 fmax=1e10 ndec=10")
    fh.append(".end")
    fh_path = out / "cnm25_rl.lst"
    fh_path.write_text("\n".join(fh) + "\n")

    summary = {
        "nets": sorted(nets),
        "conductors": {n: {k: len(v) for k, v in nets[n].items()} for n in nets},
        "fastcap": str(fc_path),
        "fasthenry": str(fh_path),
        "bulk_node": BULK_NODE,
        "cross_section": CONDUCTORS,
    }
    print(json.dumps(summary, indent=2))
    print("next: fastcap -f cnm25_caps.lst   (C matrix, good accuracy)")
    print("next: fasthenry cnm25_rl.lst      (R/L matrix; verify mesh on wide buses)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
